name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create docker container
        run: |
          docker compose -f "docker-compose.yml" up -d --build --remove-orphans
          sudo docker cp node_container:node_project/results .
        
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: Transunion-Test-Customer-Report-Artifact
          path: ./results/**

      - name: Delete docker containers
        if: always()
        run: |
          docker compose down
          docker system prune -f --volumes
