# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Create docker container
        run: docker compose -f "docker-compose-node-js.yml" up -d --build --remove-orphans

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: Transunion-Test-Customer-Report-Artifact
          path: Results/Transunion-Test-Customer-Report.csv
          retention-days: 5

      - name: Delete docker containers
        if: always()
        run: |
          docker compose down
          docker system prune -f --volumes
