# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create docker container
        run: |
          docker compose -f "docker-compose.yml" up -d --build --remove-orphans
          sudo docker cp node_container:/node_project/results/ .
        
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2-preview
        with:
          name: Transunion-Test-Customer-Report-Artifact
          path: ./Output_report.csv

      - name: Delete docker containers
        if: always()
        run: |
          docker compose down
          docker system prune -f --volumes
